#!/usr/bin/env bash

shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

export GOOSE="$shome"
export BOXCAR="$shome"
export AWSME="$shome"
export AWSME_CLI="$shome/vendor/projects/awsme_cli"

export PORT_SSHD_FILE="$shome/config/sshd.port"
export PORT_PROXY_FILE="$shome/config/proxy.port"
export SSH_AGENT_FILE="$shome/config/ssh_agent"

export VBOX_USER_HOME="$shome/.vagrant.d"
export VAGRANT_HOME="$shome/.vagrant.d"

function require_ {
  source "$shome/vendor/projects/boxcar/libexec/_boxcar"
  source "$shome/vendor/projects/awsme/libexec/_awsme"
}

require_

export PATH="$shome/bin:$PKG_HOME/bin:$PKG_HOME/sbin:$PATH"

unset BUNDLE_GEMFILE RUBYOPT
