#!/usr/bin/env bash

export GOOSE="${GOOSE:=$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)}"
export VAULT="${VAULT:=$(unset CDPATH; cd -P -- "$GOOSE/.." && pwd -P)/vault}"
export PKG_HOME="${PKG_HOME:=$(unset CDPATH; cd -P -- "$GOOSE/.." && pwd -P)/pkg}"
export YARVM="${YARVM:=$(unset CDPATH; cd -P -- "$GOOSE/.." && pwd -P)/yarvm}"
export GOOSE="${GOOSE:=$(unset CDPATH; cd -P -- "$GOOSE/.." && pwd -P)/goose}"

export BOXCAR="$GOOSE"
export AWSME="$GOOSE"
export AWSME_CLI="$GOOSE/vendor/projects/awsme_cli"

export PORT_SSHD_FILE="$GOOSE/config/sshd.port"
export PORT_PROXY_FILE="$GOOSE/config/proxy.port"
export SSH_AGENT_FILE="$GOOSE/config/ssh_agent"

export VBOX_USER_HOME="$GOOSE/.vagrant.d"
export VAGRANT_HOME="$GOOSE/.vagrant.d"

function require_ {
  source "$GOOSE/vendor/projects/boxcar/libexec/_boxcar"
  source "$GOOSE/vendor/projects/awsme/libexec/_awsme"
}

require_

export PATH="$GOOSE/bin:$PKG_HOME/bin:$PKG_HOME/sbin:$PATH"

unset BUNDLE_GEMFILE RUBYOPT

source $YARVM/libexec/_yarvm
