#!/usr/bin/env bash

#/ NAME
#/     boxcar-docker - debootstrap provisioning script

function remote_install {
  set -exfu; cd

  sudo aptitude install -y unzip

  git clone https://github.com/destructuring/goose
  cd goose
  cp config/aws.yml.example config/aws.yml
  make
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi


# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason
require _boxcar
require _boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
