#!/usr/bin/env bash

#/ NAME
#/     boxcar-yarvm - builds and installs yarvm

function remote_install {
  set -exfu; cd

  if [[ "$(uname -s)" = "Linux" ]]; then
    sudo aptitude update
    sudo aptitude install -y build-essential
    sudo aptitude install -y libxml2-dev libxslt-dev zlib1g-dev libssl-dev libreadline-dev libyaml-dev
    sudo aptitude install -y gawk libsqlite3-dev sqlite3 autoconf libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev
    sudo aptitude install -y maven openjdk-7-jre-headless > /dev/null
  fi

  if [[ "$BUILD_IMAGE_PHASE" != "install" ]]; then
    cd "$BUILD_IMAGE_PHASE"
  fi

  export VAULT="$(pwd)/vault"
  export PKG_HOME="$(pwd)/pkg"

  PATH="$PKG_HOME/bin:$PKG_HOME/sbin:$PATH"

  rm -rf yarvm
  git clone https://github.com/destructuring/yarvm yarvm

  cd yarvm
  make
  make binary
  make 1.9.3 2.0.0

  cd test
  ./run
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi


# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason
require _boxcar
require _boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  local install=""
  if [[ "$BUILD_IMAGE_PHASE" != "install" ]]; then
    intall="$BUILD_IMAGE_PHASE/"
  fi

  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
