#!/usr/bin/env bash

#/ NAME
#/     boxcar-yarvm - builds and installs yarvm

function remote_install {
  set -exfu; cd

  if [[ "$(uname -s)" = "Linux" ]]; then
    sudo aptitude install -y build-essential
  fi

  export VAULT='/opt/vault'
  export PKG_HOME="$(pwd)/pkg"

  PATH="$PKG_HOME/bin:$PKG_HOME/sbin:$PATH"

  rm -rf yarvm
  git clone git@github.com:destructuring/yarvm yarvm

  cd yarvm
  make

  make binary
  make 1.9.3 2.0.0

  cd test
  ./run 1.9.3 2.0.0
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi


# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason
require _boxcar
require _boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  ssh -F $pth_ssh_config default mkdir -p vault
  rsync -ia -e "ssh -F $pth_ssh_config" $VAULT/distfiles default:vault/
  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
