#!/usr/bin/env bash

#/ NAME
#/     boxcar-pkgsrc - builds and installs pkgsrc for boxcar

function remote_install {
  set -exfu; cd


  export VAULT='/opt/vault'
  export PKG_HOME="$(pwd)/pkg"

  rm -rf pkgsrc pkg
  cd pkgsrc
  make -f Makefile.goose bmake
  make -f Makefile.goose "$PKG_HOME/bin/bmake"
  make -f Makefile.goose packages
  make -f Makefile.goose cache
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi


# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason
require _boxcar
require _boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
