#!/usr/bin/env bash

#/ NAME
#/     boxcar-yarvm - builds and installs yarvm

function remote_build {
  set -exfu

  if [[ "$(uname -s)" = "Linux" ]]; then
    sudo -E aptitude update
    sudo -E aptitude install -y build-essential
    sudo -E aptitude install -y libxml2-dev libxslt-dev zlib1g-dev libssl-dev libreadline-dev libyaml-dev
    sudo -E aptitude install -y gawk libsqlite3-dev sqlite3 autoconf libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev
    sudo -E aptitude install -y openjdk-7-jre-headless > /dev/null
    sudo -E aptitude install -y maven > /dev/null
  fi

  export VAULT="$(pwd)/vault"
  export PKG_HOME="$(pwd)/pkg"

  PATH="$PKG_HOME/bin:$PKG_HOME/sbin:$PATH"

  mkdir -p yarvm || sudo install -o $(id -un) -g $(id -gn) -d -m 0755 yarvm
  rm -rf yarvm || true
  git clone https://github.com/destructuring/yarvm yarvm

  cd yarvm
  make
  make binary
  make install
  make test

  cd test
  ./run
}

function remote_install {
  set -exfu

  if [[ "$(uname -s)" = "Linux" ]]; then
    sudo -E aptitude update
    sudo -E aptitude install -y build-essential
    sudo -E aptitude install -y libxml2-dev libxslt-dev zlib1g-dev libssl-dev libreadline-dev libyaml-dev
    sudo -E aptitude install -y gawk libsqlite3-dev sqlite3 autoconf libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev
    sudo -E aptitude install -y openjdk-7-jre-headless > /dev/null
  fi

  export VAULT="$(pwd)/vault"
  export PKG_HOME="$(pwd)/pkg"

  PATH="$PKG_HOME/bin:$PKG_HOME/sbin:$PATH"

  mkdir -p yarvm || sudo install -o $(id -un) -g $(id -gn) -d -m 0755 yarvm
  rm -rf yarvm || true
  git clone https://github.com/destructuring/yarvm yarvm

  cd yarvm
  make
  make 1.9.3 2.0.0

  cd test
  ./run
}

if [[ "$#" = 0 ]]; then
  case "${BUILD_IMAGE_PHASE:-}" in 
    install)        
      remote_install
      exit $?         
      ;;
    build)            
      remote_build    
      exit $?         
      ;; 
    *)
      echo "ERROR: unknown build phase: $BUILD_IMAGE_PHASE" 1>&2
      exit 1
  esac
fi    

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason
require _boxcar
require _boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  ssh -F $pth_ssh_config default rm -rf ${OVERRIDE_anchor}/vault || true
  ssh -F $pth_ssh_config default mkdir -p ${OVERRIDE_anchor}/vault/packages

  local pkg_id
  local nm_os="$(ssh -F $pth_ssh_config default uname -s)"
  case "$nm_os" in
    Darwin)
      pkg_id="${nm_os}_$(ssh -F $pth_ssh_config default uname -r | cut -d. -f1)"
      ;;
    *)
      pkg_id="${nm_os}"
      ;;
  esac

  case "${BUILD_IMAGE_PHASE:-}" in 
    install)        
      rsync -ia -e "ssh -F $pth_ssh_config" $VAULT/packages/${pkg_id}$(echo $OVERRIDE_anchor | tr / _)_yarvm default:${OVERRIDE_anchor}/vault/packages/
      standard_hook "$bootstrap" "$@"
      ;;
    build)
      standard_hook "$bootstrap" "$@"
      rsync -ia -e "ssh -F $pth_ssh_config" default:${OVERRIDE_anchor}/vault/packages $VAULT/
      ;; 
  esac
}

require sub "$BASH_SOURCE" "$@"
