#!/usr/bin/env bash

#/ NAME
#/     boxcar-goose - set up the golden goose for image building

function remote_install {
  set -exfu

  mkdir -p goose || sudo install -o $(id -un) -g $(id -gn) -d -m 0755 goose
  rm -rf goose || true
  git clone https://github.com/destructuring/goose goose
  cd goose
  make
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi


# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason
require _boxcar
require _boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
