#!/usr/bin/env bash

source _jason
require _goose

nm_release="$1"; shift
nm_packer_builder="virtualbox-iso"
nm_vagrant_provider="virtualbox"
nm_build="${nm_release}-${nm_packer_builder}"
nm_box="${nm_release}-${nm_vagrant_provider}.box"

rm -rf "$GOOSE/output-${nm_build}"
rm -rf "$HOME/VirtualBox VMs/${nm_release}"

set -x

env PACKER_CACHE_DIR=$VAULT/packer_cache packer build -var proxy=http://10.0.2.2:$(cat $GOOSE/config/proxy.port) -var build_name="$nm_build" -var-file="$GOOSE/config/${nm_release}.json" $GOOSE/config/ubuntu/${nm_packer_builder}.json

cd "$GOOSE/output-${nm_build}"
(set +f; ln -nfs *.ovf box.ovf)
jq -n --arg provider "${nm_vagrant_provider}" '{"provider": $provider}' > metadata.json
tar cvfz $GOOSE/boxes/${nm_box}.tmp .
mv $GOOSE/boxes/${nm_box}.tmp $GOOSE/boxes/${nm_box}

vagrant box remove --provider ${nm_vagrant_provider} --force ${nm_release} 2>&- || true
vagrant box add ${nm_release} $GOOSE/boxes/${nm_box}
