#!/usr/bin/env bash

source _jason
require _goose

nm_release="precise"
nm_provider="aws"

vagrant box remove ${nm_release} ${nm_provider} 2>&- || true
vagrant box add ${nm_release} $shome/boxes/${nm_provider}.box
train --provider ${nm_provider} --release ${nm_release} --clean docker:${nm_release}
train --provider ${nm_provider} --release ${nm_release} clean docker
