#!/usr/bin/env bash

#/ NAME
#/     list-vagrants - order vagrants by provider and then name

source _jason

function main {
  vagrant box list | while read -r a b; do echo "$b $a $b"; done | sort | awk '{print $2,$3}' | talign
}

require sub "$BASH_SOURCE" "$@"
