#!/usr/bin/env bash

#/ NAME
#/     packager-virtualbox-trusty - passes an argument to boxcar-virtualbox

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

exec $shome/bin/build virtualbox trusty
