#!/bin/bash

#/ NAME
#/     puddle-cache -- dowload pip package and create index
#/
#/ SYNOPSIS
#/     puddle cache [packages...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason

# entry point
function main {
  local pth_cache="$shome/vendor/puddle"

  set +u; source $shome/bin/activate; set -u
  mkdir -p "$pth_cache"
  if [[ "$#" = 0 ]]; then
    set -- -r requirements.txt
  fi

  if [[ "$#" -gt  0 ]]; then
    pip install --download-directory "$pth_cache" "$@"
  fi
}

require sub "$BASH_SOURCE" "$@"
