#!/bin/bash

#/ NAME
#/     puddle-install -- install cached package
#/
#/ SYNOPSIS
#/     puddle install [packages...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source _jason

# entry point
function main {
  local pth_cache="$shome/vendor/puddle"

  set +u; source $shome/bin/activate; set -u

  if [[ "$#" = 0 ]]; then
    set -- -r requirements.txt
  fi

  if [[ "$#" -gt  0 ]]; then
    pip install --upgrade --find-links=file://$pth_cache "$@"
  fi

  pip freeze > $shome/requirements.txt.exact
}

require sub "$BASH_SOURCE" "$@"
