#!/usr/bin/env bash

source _jason
require _goose

unset BUNDLE_BIN_PATH GEM_HOME GEM_PATH _ORIGINAL_GEM_PATH RBENV_DIR

if [[ "$#" > 0 && "${1%%-*}" != "" ]]; then
  exec "$@"
else
  exec "$SHELL" "$@"
fi
