#!/usr/bin/env bash

#/ NAME
#/     update-awsbox - add the latest aws vagrant boxes

source _jason

function main {
  if [[ "$#" = 0 ]]; then
    set -- precise
  fi

  for r in "$@"; do  
    set +f
    for a in $VAULT/boxcar/$r/aws/*.box; do 
      if [[ -r "$a" ]]; then
        vagrant box remove --provider aws --force $r-$(basename $a .box) 2>&1 > /dev/null || true
        vagrant box add $r-$(basename $a .box) $a 
      fi
    done
    set -f
  done
}

require sub "$BASH_SOURCE" "$@"
