#!/usr/bin/env bash

source _jason
require _goose

pth_vagrant="$(bundle exec which vagrant 2>&- || true)"
if [[ "$pth_vagrant" = "$shome/bin/vagrant" ]]; then
  printf 'ERROR: vagrant not found, run make' 1>&2
  exit 1
fi

exec bundle exec vagrant "$@"
