#!/bin/sh
: ${GOOSE="/opt/goose"}
cd ${GOOSE}/goose
exec chpst -e ${GOOSE}/service/sshd/env ${GOOSE}/bin/shell vendor/projects/offline/bin/setup-sshd ${GOOSE}/goose/config/sshd.port ${GOOSE}/goose/config/authorized_keys
