#!/bin/sh
: ${GOLDEN_PATH="/opt/goose"}
cd ${GOLDEN_PATH}/goose
exec chpst -e ${GOLDEN_PATH}/service/proxy/env ${GOLDEN_PATH}/bin/shell vendor/projects/offline/bin/setup-squid ${GOLDEN_PATH}/goose/config/proxy.port
